// Generates src/hatches.js from the USCS hatch tiles in assets/hatches/.
// Each source file is a 104x93 tile wrapped in a scaling <g> and a <script>
// that read ?scale= from the URL (the old viewer loaded them via <object>).
// We keep only the tile contents so the renderer can inline them as <pattern>s.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../assets/hatches/', import.meta.url);
const hatches = {};
for (const file of readdirSync(dir).filter(f => f.endsWith('.svg')).sort()) {
    const svg = readFileSync(new URL(file, dir), 'utf8');
    const tile = svg.match(/<pattern[^>]*width="(\d+)"[^>]*height="(\d+)"[^>]*>([\s\S]*?)<\/pattern>/);
    if (!tile) throw new Error(`no <pattern> tile in ${file}`);
    const body = tile[3]
        .replace(/\s+/g, ' ')
        .replace(/\s*=\s*/g, '=')
        .replace(/>\s+</g, '><')
        .trim();
    hatches[file.replace(/\.svg$/, '')] = { width: Number(tile[1]), height: Number(tile[2]), body };
}

const out = `// Generated by scripts/build-hatches.js from assets/hatches/*.svg — do not edit by hand.
export const HATCH_TILES = ${JSON.stringify(hatches, null, 1)};
`;
writeFileSync(new URL('../src/hatches.js', import.meta.url), out);
console.log(`wrote src/hatches.js (${Object.keys(hatches).join(', ')})`);
