// Generates src/hatches.js from the procedurally drawn hatch tiles:
//   scripts/uscs-art.js       USCS soils and dual symbols, in the Caltrans legend style
//   scripts/lithology-art.js  fill, man-made and other materials, and rock (FGDC style)
// Run after changing either:  npm run build:hatches
// (The earlier USCS tiles, SVG files taken from the old coastal_database viewer,
// were replaced by uscs-art.js in Sep. 2026.)
import { writeFileSync } from 'node:fs';
import { uscsArt } from './uscs-art.js';
import { lithologyArt } from './lithology-art.js';
import { LITHOLOGY } from '../src/lithology.js';

const hatches = { ...uscsArt() };

// Non-USCS materials and rock must match src/lithology.js exactly.
const art = lithologyArt();
const expected = Object.keys(LITHOLOGY);
const missing = expected.filter(code => !art[code]);
const extra = Object.keys(art).filter(code => !LITHOLOGY[code]);
if (missing.length || extra.length) throw new Error(`lithology art out of step with src/lithology.js: missing ${missing.join(', ') || '-'}; extra ${extra.join(', ') || '-'}`);
for (const code of expected) {
    if (hatches[code]) throw new Error(`${code} is both a USCS tile and a lithology code`);
    hatches[code] = art[code];
}

// Merges <line>s, and <path>s with the same stroke and fill, into one <path> per
// style. The drawing is identical; the markup (bundled into the web page) is far
// smaller.
function compact(body) {
    const groups = new Map();
    const keep = [];
    const key = attrs => attrs.replace(/\s+d="[^"]*"/, '');
    const re = /<line x1="([^"]+)" y1="([^"]+)" x2="([^"]+)" y2="([^"]+)"([^>]*)\/>|<path d="([^"]+)"([^>]*)\/>|<[^>]+>/g;
    let m;
    while ((m = re.exec(body))) {
        if (m[1] !== undefined) {
            const k = `fill="none"${m[5]}`;
            if (!groups.has(k)) groups.set(k, []);
            groups.get(k).push(`M${m[1]} ${m[2]}L${m[3]} ${m[4]}`);
        } else if (m[6] !== undefined) {
            const k = key(m[7]).trim();
            if (!groups.has(k)) groups.set(k, []);
            groups.get(k).push(m[6].replace(/\s*([MLQTZqtAa])\s*/g, '$1').trim());
        } else {
            keep.push(m[0]);
        }
    }
    const merged = [...groups].map(([attrs, ds]) => `<path d="${ds.join('')}" ${attrs}/>`);
    return keep.join('') + merged.join('');
}
for (const tile of Object.values(hatches)) tile.body = compact(tile.body);

const out = `// Generated by scripts/build-hatches.js from scripts/uscs-art.js and scripts/lithology-art.js — do not edit by hand.
export const HATCH_TILES = ${JSON.stringify(hatches, null, 1)};
`;
writeFileSync(new URL('../src/hatches.js', import.meta.url), out);
console.log(`wrote src/hatches.js (${Object.keys(hatches).length} tiles)`);
