// Generates src/hatches.js from the USCS hatch tiles in assets/hatches/ and the
// procedurally drawn tiles for other materials and rock (scripts/lithology-art.js).
// Each source file is a 104x93 tile wrapped in a scaling <g> and a <script>
// that read ?scale= from the URL (the old viewer loaded them via <object>).
// We keep only the tile contents so the renderer can inline them as <pattern>s.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { lithologyArt } from './lithology-art.js';
import { LITHOLOGY } from '../src/lithology.js';

const dir = new URL('../assets/hatches/', import.meta.url);
const hatches = {};
for (const file of readdirSync(dir).filter(f => f.endsWith('.svg')).sort()) {
    const svg = readFileSync(new URL(file, dir), 'utf8');
    const tile = svg.match(/<pattern[^>]*width="(\d+)"[^>]*height="(\d+)"[^>]*>([\s\S]*?)<\/pattern>/);
    if (!tile) throw new Error(`no <pattern> tile in ${file}`);
    const body = tile[3]
        .replace(/\s+/g, ' ')
        .replace(/\s*=\s*/g, '=')
        .replace(/>\s+</g, '><')
        .trim();
    hatches[file.replace(/\.svg$/, '')] = { width: Number(tile[1]), height: Number(tile[2]), body };
}

// Non-USCS materials and rock: drawn procedurally (scripts/lithology-art.js).
const art = lithologyArt();
const expected = Object.keys(LITHOLOGY);
const missing = expected.filter(code => !art[code]);
const extra = Object.keys(art).filter(code => !LITHOLOGY[code]);
if (missing.length || extra.length) throw new Error(`lithology art out of step with src/lithology.js: missing ${missing.join(', ') || '-'}; extra ${extra.join(', ') || '-'}`);
for (const code of expected) {
    if (hatches[code]) throw new Error(`${code} is both a USCS tile and a lithology code`);
    hatches[code] = art[code];
}

const out = `// Generated by scripts/build-hatches.js from assets/hatches/*.svg and scripts/lithology-art.js — do not edit by hand.
export const HATCH_TILES = ${JSON.stringify(hatches, null, 1)};
`;
writeFileSync(new URL('../src/hatches.js', import.meta.url), out);
console.log(`wrote src/hatches.js (${Object.keys(hatches).join(', ')})`);
