// Generates src/font-metrics.js: per-character advance widths for Arimo
// (metric-compatible with Arial / Liberation Sans). The renderer measures text
// with this table instead of the DOM, so layout is identical in every browser
// and on the server. Re-run only if the font or character range changes.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import opentype from 'opentype.js';

const require = createRequire(import.meta.url);
const fontDir = require.resolve('@fontsource/arimo/package.json').replace(/package\.json$/, 'files/');

function advances(file) {
    const buf = readFileSync(fontDir + file);
    const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
    const widths = {};
    // Printable ASCII, Latin-1 supplement, and a few symbols used in logs.
    const codepoints = [];
    for (let c = 0x20; c <= 0x7e; c++) codepoints.push(c);
    for (let c = 0xa0; c <= 0xff; c++) codepoints.push(c);
    codepoints.push(0x2013, 0x2014, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2026, 0x2212, 0x2248, 0x2264, 0x2265, 0x25bd, 0x03b3);
    for (const c of codepoints) {
        const glyph = font.charToGlyph(String.fromCodePoint(c));
        if (glyph && glyph.index !== 0) widths[c] = glyph.advanceWidth;
    }
    return { unitsPerEm: font.unitsPerEm, widths };
}

const regular = advances('arimo-latin-400-normal.woff');
const bold = advances('arimo-latin-700-normal.woff');

const out = `// Generated by scripts/build-metrics.js — do not edit by hand.
// Advance widths (font units) for Arimo, metric-compatible with Arial.
export const UNITS_PER_EM = ${regular.unitsPerEm};
export const REGULAR = ${JSON.stringify(regular.widths)};
export const BOLD = ${JSON.stringify(bold.widths)};
`;
writeFileSync(new URL('../src/font-metrics.js', import.meta.url), out);
console.log(`wrote src/font-metrics.js (${Object.keys(regular.widths).length} glyphs)`);
