// Built-in hatches for materials other than USCS soils: fill and man-made
// materials, natural materials, non-material intervals, and rock. Generated
// from the reviewed "Hatch library proposal" spreadsheet (Sep. 2026); the tile
// artwork is drawn by scripts/lithology-art.js into src/hatches.js.
//   fallback: the hatch drawn when this code has no tile of its own
//   keywords: description words that point to it (the reviewed inference rules are in materials.js)
// LOAM and PUMICE were added after the review of NGL descriptions (Sep. 2026).
export const LITHOLOGY = {
    FILL: { name: "Fill", group: "Fill and man-made", fallback: null, keywords: ["fill"] },
    FILL_HYD: { name: "Hydraulic fill", group: "Fill and man-made", fallback: "FILL", keywords: ["hydraulic fill"] },
    FILL_ENG: { name: "Engineered fill", group: "Fill and man-made", fallback: "FILL", keywords: ["engineered fill", "compacted fill", "structural fill"] },
    FILL_UNDOC: { name: "Undocumented fill", group: "Fill and man-made", fallback: "FILL", keywords: ["undocumented fill", "uncontrolled fill"] },
    DEBRIS: { name: "Debris, rubble or waste", group: "Fill and man-made", fallback: "FILL", keywords: ["debris", "rubble", "waste", "refuse", "landfill"] },
    ASPHALT: { name: "Asphalt pavement", group: "Fill and man-made", fallback: null, keywords: ["asphalt", "pavement", "A.C."] },
    CONCRETE: { name: "Concrete", group: "Fill and man-made", fallback: null, keywords: ["concrete", "P.C.C."] },
    BASE_COURSE: { name: "Aggregate base course", group: "Fill and man-made", fallback: "FILL", keywords: ["base course", "aggregate base", "baserock"] },
    TOPSOIL: { name: "Topsoil", group: "Natural materials", fallback: null, keywords: ["topsoil", "top soil"] },
    SHELL: { name: "Shell or shelly soil", group: "Natural materials", fallback: null, keywords: ["shell", "shells", "coquina", "shell hash"] },
    COBBLES: { name: "Cobbles and boulders", group: "Natural materials", fallback: null, keywords: ["cobble", "cobbles", "boulder", "boulders"] },
    WOOD: { name: "Wood or organic debris", group: "Natural materials", fallback: null, keywords: ["wood", "timber", "roots", "organic debris"] },
    ASH: { name: "Volcanic ash or tephra", group: "Natural materials", fallback: null, keywords: ["ash", "tephra"] },
    CEMENTED: { name: "Cemented soil, caliche or hardpan", group: "Natural materials", fallback: null, keywords: ["cemented", "caliche", "hardpan", "duripan"] },
    LOESS: { name: "Loess", group: "Natural materials", fallback: null, keywords: ["loess"] },
    MARL: { name: "Marl", group: "Natural materials", fallback: null, keywords: ["marl"] },
    DIATOMITE: { name: "Diatomaceous earth", group: "Natural materials", fallback: null, keywords: ["diatomaceous", "diatomite (soil)"] },
    BENTONITE: { name: "Bentonite", group: "Natural materials", fallback: null, keywords: ["bentonite"] },
    LOAM: { name: "Loam", group: "Natural materials", fallback: null, keywords: ["loam", "sandy loam", "silt loam", "clay loam"] },
    QUICK_CLAY: { name: "Sensitive (quick) clay", group: "Natural materials", fallback: null, keywords: ["sensitive clay", "quick clay"] },
    WATER: { name: "Water", group: "Non-material intervals", fallback: null, keywords: ["water (over-water borings)"] },
    NO_RECOVERY: { name: "No recovery", group: "Non-material intervals", fallback: null, keywords: ["no recovery", "not recovered"] },
    VOID: { name: "Void or cavity", group: "Non-material intervals", fallback: null, keywords: ["void", "cavity"] },
    ROCK: { name: "Rock (unspecified)", group: "Rock: category", fallback: null, keywords: ["rock", "bedrock"] },
    ROCK_SED: { name: "Sedimentary rock", group: "Rock: category", fallback: "ROCK", keywords: ["sedimentary rock"] },
    ROCK_IGN: { name: "Igneous rock", group: "Rock: category", fallback: "ROCK", keywords: ["igneous rock"] },
    ROCK_MET: { name: "Metamorphic rock", group: "Rock: category", fallback: "ROCK", keywords: ["metamorphic rock"] },
    WEATHERED: { name: "Weathered rock or saprolite", group: "Rock: transitional", fallback: "ROCK", keywords: ["weathered rock", "saprolite", "residual soil", "decomposed"] },
    IGM: { name: "Intermediate geomaterial", group: "Rock: transitional", fallback: "ROCK", keywords: ["intermediate geomaterial", "IGM", "very dense (soft rock)"] },
    SANDSTONE: { name: "Sandstone", group: "Rock: sedimentary (clastic)", fallback: "ROCK_SED", keywords: ["sandstone"] },
    SHALE: { name: "Shale", group: "Rock: sedimentary (clastic)", fallback: "ROCK_SED", keywords: ["shale"] },
    SILTSTONE: { name: "Siltstone", group: "Rock: sedimentary (clastic)", fallback: "ROCK_SED", keywords: ["siltstone"] },
    MUDSTONE: { name: "Mudstone", group: "Rock: sedimentary (clastic)", fallback: "ROCK_SED", keywords: ["mudstone"] },
    CLAYSTONE: { name: "Claystone", group: "Rock: sedimentary (clastic)", fallback: "ROCK_SED", keywords: ["claystone"] },
    CONGLOMERATE: { name: "Conglomerate", group: "Rock: sedimentary (clastic)", fallback: "ROCK_SED", keywords: ["conglomerate"] },
    BRECCIA: { name: "Breccia", group: "Rock: sedimentary (clastic)", fallback: "ROCK_SED", keywords: ["breccia (sedimentary)"] },
    LIMESTONE: { name: "Limestone", group: "Rock: sedimentary (chemical/organic)", fallback: "ROCK_SED", keywords: ["limestone"] },
    DOLOMITE: { name: "Dolomite", group: "Rock: sedimentary (chemical/organic)", fallback: "ROCK_SED", keywords: ["dolomite", "dolostone"] },
    CHALK: { name: "Chalk", group: "Rock: sedimentary (chemical/organic)", fallback: "ROCK_SED", keywords: ["chalk"] },
    CHERT: { name: "Chert", group: "Rock: sedimentary (chemical/organic)", fallback: "ROCK_SED", keywords: ["chert"] },
    COAL: { name: "Coal or lignite", group: "Rock: sedimentary (chemical/organic)", fallback: "ROCK_SED", keywords: ["coal", "lignite"] },
    EVAPORITE: { name: "Evaporite (gypsum, anhydrite, halite)", group: "Rock: sedimentary (chemical/organic)", fallback: "ROCK_SED", keywords: ["gypsum", "anhydrite", "halite", "evaporite"] },
    GRANITE: { name: "Granite", group: "Rock: igneous (intrusive)", fallback: "ROCK_IGN", keywords: ["granite", "granitic"] },
    GRANODIORITE: { name: "Granodiorite", group: "Rock: igneous (intrusive)", fallback: "ROCK_IGN", keywords: ["granodiorite"] },
    DIORITE: { name: "Diorite", group: "Rock: igneous (intrusive)", fallback: "ROCK_IGN", keywords: ["diorite"] },
    GABBRO: { name: "Gabbro", group: "Rock: igneous (intrusive)", fallback: "ROCK_IGN", keywords: ["gabbro"] },
    PERIDOTITE: { name: "Peridotite", group: "Rock: igneous (intrusive)", fallback: "ROCK_IGN", keywords: ["peridotite"] },
    BASALT: { name: "Basalt", group: "Rock: igneous (extrusive)", fallback: "ROCK_IGN", keywords: ["basalt"] },
    ANDESITE: { name: "Andesite", group: "Rock: igneous (extrusive)", fallback: "ROCK_IGN", keywords: ["andesite"] },
    DACITE: { name: "Dacite", group: "Rock: igneous (extrusive)", fallback: "ROCK_IGN", keywords: ["dacite"] },
    RHYOLITE: { name: "Rhyolite", group: "Rock: igneous (extrusive)", fallback: "ROCK_IGN", keywords: ["rhyolite"] },
    TUFF: { name: "Tuff", group: "Rock: igneous (pyroclastic)", fallback: "ROCK_IGN", keywords: ["tuff", "welded tuff"] },
    VOLC_BRECCIA: { name: "Volcanic breccia", group: "Rock: igneous (pyroclastic)", fallback: "ROCK_IGN", keywords: ["volcanic breccia", "agglomerate"] },
    SCORIA: { name: "Scoria", group: "Rock: igneous (pyroclastic)", fallback: "ROCK_IGN", keywords: ["scoria (rock)"] },
    PUMICE: { name: "Pumice", group: "Rock: igneous (pyroclastic)", fallback: "ROCK_IGN", keywords: ["pumice"] },
    SLATE: { name: "Slate", group: "Rock: metamorphic (foliated)", fallback: "ROCK_MET", keywords: ["slate"] },
    PHYLLITE: { name: "Phyllite", group: "Rock: metamorphic (foliated)", fallback: "ROCK_MET", keywords: ["phyllite"] },
    SCHIST: { name: "Schist", group: "Rock: metamorphic (foliated)", fallback: "ROCK_MET", keywords: ["schist"] },
    GNEISS: { name: "Gneiss", group: "Rock: metamorphic (foliated)", fallback: "ROCK_MET", keywords: ["gneiss"] },
    QUARTZITE: { name: "Quartzite", group: "Rock: metamorphic (non-foliated)", fallback: "ROCK_MET", keywords: ["quartzite"] },
    MARBLE: { name: "Marble", group: "Rock: metamorphic (non-foliated)", fallback: "ROCK_MET", keywords: ["marble"] },
    HORNFELS: { name: "Hornfels", group: "Rock: metamorphic (non-foliated)", fallback: "ROCK_MET", keywords: ["hornfels"] },
    SERPENTINITE: { name: "Serpentinite", group: "Rock: metamorphic (non-foliated)", fallback: "ROCK_MET", keywords: ["serpentinite", "serpentine"] },
    GREENSTONE: { name: "Greenstone or amphibolite", group: "Rock: metamorphic (non-foliated)", fallback: "ROCK_MET", keywords: ["greenstone", "amphibolite"] },
    FAULT_GOUGE: { name: "Fault gouge", group: "Rock: fault rock", fallback: "ROCK", keywords: ["gouge", "fault gouge"] },
    FAULT_BRECCIA: { name: "Fault breccia", group: "Rock: fault rock", fallback: "ROCK", keywords: ["fault breccia", "sheared zone"] },
    MYLONITE: { name: "Mylonite", group: "Rock: fault rock", fallback: "ROCK_MET", keywords: ["mylonite"] },
};

// Group headings in the order they are listed.
export const LITHOLOGY_GROUPS = ["Fill and man-made", "Natural materials", "Non-material intervals", "Rock: category", "Rock: transitional", "Rock: sedimentary (clastic)", "Rock: sedimentary (chemical/organic)", "Rock: igneous (intrusive)", "Rock: igneous (extrusive)", "Rock: igneous (pyroclastic)", "Rock: metamorphic (foliated)", "Rock: metamorphic (non-foliated)", "Rock: fault rock"];
